### ISSUE TITLE
Can't add ssh keys

### ISSUE THREAD

**Issue by adhi-thirumala** [theOGognf/private_poker#23]
After running
``ssh -i ~/.ssh/poker_id_rsa -o SendEnv=PUBLIC_KEY -p 9090 username@hostname``
*removed username and hostname from command for security
i get the following output

``/usr/local/bin/claim_user: line 10: can't create /home/foo/ssh/authorized_keys: nonexistent directory
Connection to hostname closed.``

**Comment by adhi-thirumala** [comment]
another odd issue that seems to not make a difference is that doing ``docker inspect --format='{{.NetworkSettings.IPAddress}}' ``poker does not get me anything even though I have initialized the container with ``docker run -d --name poker -p 9090:22 --rm ognf/poker:latest``

**Comment by theOGognf** [comment]
What OS is the host? Can you provide the output of  `docker exec poker ./create_user $username` as well? PS your username is showing in your path if that matters

**Comment by theOGognf** [comment]
Assuming this is resolved since I can't reproduce
